development: &default
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>

test:
  <<: *default
  database: hound_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5).to_i, ENV.fetch("DB_POOL", 5).to_i].max %>
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
